/*
 exports.WX_APPID='wxb7b8e7a455a97831'
 exports.WX_APPSECRET='50b252d448d17c1105561331dc86e14d'

 exports.QQ_APPID='1105484881'
 exports.QQ_APPSECRET='UPf3TPm4DZP8Bi3o'

 exports.WB_APPID='1238044455'
 exports.WB_APPSECRET='630c45e5edcb32349408ee0e669bc5ee'*/

exports.TOP_SIGN = '9890117'
exports.TOP_KEY = '23385797'
exports.TOP_SECRET = '5b9f864b4a7dd77bf2ba364081560f9f'

//阿里百川
exports.TOP_APPKEY = '23410258'
exports.TOP_APPSECRET = 'b37f30d67f59f3f276137589daadab6c'

exports.ALI_AK_ID = 'UsXz7faYtoLbo7TV'
exports.ALI_AK_SECRET = 'PCc4ZVTNw25uLwhADyNfhSh8KvNt75'

exports.ALI_OSS_BUCKET_AVATAR = '/avatar/'

//bcrypt saltRounds
exports.BCRYPT_SALT_ROUNDS = 12

// JWT密钥
exports.JWT_TOKEN_SECRET = 'tNYnQbR8uN4tPbCXrywTS6LyWt40qLWs'
exports.JWT_VALID_DAYS = 1

/*
 exports.OO_TYPE_TRANSFER = 'OO_TYPE_TRANSFER'
 exports.OO_TYPE_DELIVERY = 'OO_TYPE_DELIVERY'
 exports.OO_TYPE_CREDIT = 'OO_TYPE_CREDIT'

 exports.DEAL_TYPE_BUY = 'DEAL_TYPE_BUY'
 exports.DEAL_TYPE_SELL = 'DEAL_TYPE_SELL'

 exports.CREDIT_CONSUME_TYPE_CREDITEE_USED = 'CREDIT_CONSUME_TYPE_CREDITEE_USED'
 exports.CREDIT_CONSUME_TYPE_WAREHOUSE_CONFIRM = 'CREDIT_CONSUME_TYPE_WAREHOUSE_CONFIRM'
 exports.CREDIT_CONSUME_TYPE_CREDITEE_RETURN = 'CREDIT_CONSUME_TYPE_CREDITEE_RETURN'
 exports.CREDIT_CONSUME_TYPE_CREDITEE_ACCEPT = 'CREDIT_CONSUME_TYPE_CREDITEE_ACCEPT'

 exports.CREDIT_END_TYPE_RETURN = 'CREDIT_END_TYPE_RETURN'
 exports.CREDIT_END_TYPE_ACCEPT = 'CREDIT_END_TYPE_ACCEPT'

 exports.USER_INFO_TYPE_AVATAR = 'USER_INFO_TYPE_AVATAR'
 exports.USER_INFO_TYPE_NICKNAME = 'USER_INFO_TYPE_NICKNAME'
 exports.USER_INFO_TYPE_COMPANYNAME = 'USER_INFO_TYPE_COMPANYNAME'
 exports.USER_INFO_TYPE_MOBILE = 'USER_INFO_TYPE_MOBILE'
 exports.USER_INFO_TYPE_ADDRESS = 'USER_INFO_TYPE_ADDRESS'
 exports.USER_INFO_TYPE_SIGNATURE = 'USER_INFO_TYPE_SIGNATURE'
 exports.USER_INFO_TYPE_BUSINESS = 'USER_INFO_TYPE_BUSINESS'
 exports.USER_INFO_TYPE_NOTICE = 'USER_INFO_TYPE_NOTICE'
 exports.USER_INFO_TYPE_ADDRESS = 'api.ci.yue-qiu'

 */

